### ISSUE TITLE
qn(labs): Feedback - Onboarding Lab 1

### ISSUE THREAD

**Issue by nickelpro** [NYU-Processor-Design/nyu-processor-design.github.io#1]
Onboarding Lab 1 concerns CMake and has a complete description, but needs a run through and feedback from actual Proc Design team members.

Notably:
* We should probably have more exercises that allow students to write more of there own CMake code.
* Maybe introduce more complex CMake functionality? Functions? Conditionals? Loops?

Or perhaps those things should be split out into their own optional lab

**Comment by rishyak** [comment]
More CMake exercises will be great, `hello_world` is a trivial example. It barely takes half-hour to complete. The challenge is getting used to git/github, setting up dependencies, etc. A slow first week is fine and encouraged to avoid overstimulation. More exercises can be optional.

More complex CMake exercises would be great, especially for those looking to be stack czars; I assume they will be repository managers and they **should** know the toolchain to an intermediate level. These should definitely be their own lab.

**Comment by nickelpro** [comment]
So not so much more lab exercises in the week 1 cmake lab, but a separate lab (or optional challenge/tutorial) that does more and explores the topic further?

**Comment by rishyak** [comment]
Either a separate optional lab or an optional section in lab 1 - both have the same effect. 

A challenge I can think of to test that onboarding members have *reallly* internalised is to provide a semi-complicated codebase (say 2-4 header files with corresponding source code and one "main" file) without any build instructions. Members have to write a CML to compile it and run it.

**Comment by nickelpro** [comment]
I had a similar idea, for now let's say it gets pushed into its own thing (maybe a link from Lab 1, "For further exercises with this...")

I'll keep this issue open as a tracker that we need more exercises in this vein. Either I'll hit in in my second round through the labs (once we have something on paper for all of them) or someone who's interested in taking over a documentation role can look into it.
