### ISSUE TITLE
qn(labs): lab 1 confusion

### ISSUE THREAD

**Issue by NickyDCFP** [NYU-Processor-Design/nyu-processor-design.github.io#30]
I had some confusion when working on the final portion of Lab 1 (`cmake` and toolchain). In **Part 3: Adding More Files**, it wasn't intuitive to me that I could include `name.hpp` into both `hello.cpp` and `name.cpp` and, because of how `cmake` works, the implementation present in `name.cpp` would be accessible from `hello.cpp`. For this reason, when reading through the lab, I automatically assumed that I was supposed to include `name.hpp` in only `name.cpp`, which became a confusing issue for a while. Therefore, it might be useful to emphasize that `name.hpp` should be included in both `name.cpp` and `name.cpp`, and perhaps even that there should only be one `main` function.

**Comment by nickelpro** [comment]
So this is more of a "how C++ works" thing than "how `cmake` works". Without `cmake`, this would work the exact same way if you were invoking `gcc` directly, ie, `gcc -o hello_world name.cpp hello.cpp` would have the same semantics.

This team doesn't list C++ as a necessary skill, so maybe the real answer is that we need a brief intro to the semantics of C++?

My only concern is that our docs are definitely not the place to try to teach people C++, so any intro would have to immediately transition into "and here's where to look for more resources"
